---
# Install Redis from the official Redis repository for Debian/Ubuntu
# See: https://redis.io/docs/latest/operate/oss_and_stack/install/archive/install-redis/install-redis-on-linux/

- name: (Debian/Ubuntu) Install python3-debian for deb822_repository
  ansible.builtin.apt:
    name: python3-debian
    state: present

- name: (Debian/Ubuntu) Add official Redis repository
  ansible.builtin.deb822_repository:
    name: redis
    types: deb
    uris: https://packages.redis.io/deb
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: https://packages.redis.io/gpg
    state: present

- name: (Debian/Ubuntu) Install Redis
  ansible.builtin.apt:
    name: redis
    state: present
    update_cache: true
