---
# tasks file for inmotionhosting.redis

- name: Configure package repository and install Redis
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- name: Ensure Redis config directory exists
  ansible.builtin.file:
    path: /etc/redis
    state: directory
    owner: redis
    group: redis
    mode: "0770"

- name: Configure Redis
  ansible.builtin.template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: "0640"
  notify: Restart redis

- name: Enable and start redis service
  ansible.builtin.service:
    name: redis
    enabled: true
    state: started
