---
# tasks file for inmotionhosting.redis

- name: Include variables and set facts
  ansible.builtin.include_tasks: facts.yml

- name: Handle os_family errata
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- name: Ensure Redis config directory exists
  ansible.builtin.file:
    path: "{{ redis_conf | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure Redis
  ansible.builtin.template:
    src: redis.conf.j2
    dest: "{{ redis_conf }}"
    owner: redis
    group: redis
    mode: "0640"
  notify: Restart redis

- name: Include systemd restart configuation
  ansible.builtin.include_tasks: systemd.yml
  when: >-
    ( redis_systemd_restart|default(False)
    or systemd_restart|default(False) )
    and systemd_restart_setting is defined

- name: Enable and start redis service
  ansible.builtin.service:
    name: "{{ redis_daemon }}"
    enabled: true
    state: started
