---
# tasks file for inmotionhosting.redis

- name: Include variables and set facts
  ansible.builtin.include_tasks: facts.yml

- name: Handle os_family errata
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Configure Redis
  ansible.builtin.template:
    src: redis.conf.j2
    dest: "{{ redis_conf }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart redis

- name: Include systemd restart configuation
  ansible.builtin.include_tasks: systemd.yml
  when: >-
    ( redis_systemd_restart|default(False)
    or systemd_restart|default(False) )
    and systemd_restart_setting is defined

- name: Enable and start redis service
  ansible.builtin.service:
    name: "{{ redis_daemon }}"
    state: started
    enabled: true
