---
# Install Redis from the official Redis repository for RHEL/CentOS/AlmaLinux/RockyLinux
# See: https://redis.io/docs/latest/operate/oss_and_stack/install/install-stack/rpm/

- name: (RedHat) Import Redis GPG key
  ansible.builtin.rpm_key:
    key: https://packages.redis.io/gpg
    state: present

- name: (RedHat) Add official Redis repository
  ansible.builtin.yum_repository:
    name: redis
    description: Redis
    baseurl: "https://packages.redis.io/rpm/rockylinux{{ ansible_facts['distribution_major_version'] }}"
    gpgcheck: true
    gpgkey: https://packages.redis.io/gpg
    enabled: true
    state: present

- name: (RedHat) Install Redis
  ansible.builtin.dnf:
    name: "{{ redis_package }}"
    state: present
