---
- name: (RedHat) Install Remi repo
  ansible.builtin.dnf:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: (RedHat) Install Redis
  ansible.builtin.dnf:
    name: "@redis:{{ redis_module_stream }}"
    state: present
