---
- name: (RedHat) Install Remi repo
  ansible.builtin.package:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: (RedHat) Install Redis
  ansible.builtin.package:
    name: "{{ redis_packages }}"
    enablerepo: "remi"
    state: present
  register: redis_installed
