# tasks/facts.yml

- name: (Debian/Python 3) Install python-apt package
  ansible.builtin.package:
    name: python3-apt
    state: present
  when:
    - ansible_python_version is version('3.0', '>=')
    - ansible_os_family == "Debian"

- name: (Debian/Python 2) Install python-apt package
  ansible.builtin.package:
    name: python-apt
    state: present
  when:
    - ansible_python_version is version('3.0', '<')
    - ansible_os_family == "Debian"

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Set and sanitize systemd version facts
  ansible.builtin.set_fact:
    systemd_version: >-
      {{ ansible_facts.packages['systemd'][0].version }}

- name: Creates service directory
  ansible.builtin.file:
    path: /etc/systemd/system/{{ redis_daemon }}.service.d
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Create service file
  ansible.builtin.template:
    src: etc/systemd/restart.conf.j2
    dest: /etc/systemd/system/{{ redis_daemon }}.service.d/restart.conf
    owner: root
    group: root
    mode: "0600"
  notify: Restart redis
