name: Ansible Molecule Pipeline

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  molecule:
    name: Molecule Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2404
          - debian12
          - almalinux9
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: pip install -r requirements.txt

      - name: Run Molecule Test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
