name: Ansible Molecule Pipeline

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]
  schedule:
    # Run every Tuesday at 4:00 PM UTC
    - cron: '0 16 * * 2'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  molecule:
    name: Molecule Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - geerlingguy/docker-ubuntu2404-ansible:latest
          - combssm/docker-debian12-ansible:latest
          - combssm/docker-almalinux9-ansible:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip install -r requirements.txt

      - name: Run Molecule Test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_IMAGE: ${{ matrix.distro }}

  release:
    name: Publish to Galaxy
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: molecule
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Publish to Ansible Galaxy
        run: >-
          ansible-galaxy role import
          --token ${{ secrets.GALAXY_API_KEY }}
          ${{ github.repository_owner }}
          ${{ github.event.repository.name }}
